// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiThreadPriority
    {
        eThreadPriorityNone = 0,
        eThreadPriorityAudio,
        eThreadPriorityCapture,
        eThreadPriorityDistribution,
        eThreadPriorityGames,
        eThreadPriorityPlayback,
        eThreadPriorityProAudio,
        eThreadPriorityWindowManager
    }
}
