// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet.Wasapi
{
    [StructLayout(LayoutKind.Explicit, Size = 72)]
    public unsafe partial struct PaWasapiStreamInfo
    {
        [FieldOffset(0)] public uint size;

        [FieldOffset(4)] public PaHostApiTypeId hostApiType;

        [FieldOffset(8)] public uint version;

        [FieldOffset(12)] public uint flags;

        [FieldOffset(16)] public uint channelMask;

        [FieldOffset(24)] public delegate* unmanaged[Cdecl]<void*, int, void*, int, void*, void> hostProcessorOutput;

        [FieldOffset(32)] public delegate* unmanaged[Cdecl]<void*, int, void*, int, void*, void> hostProcessorInput;

        [FieldOffset(40)] public PaWasapiThreadPriority threadPriority;

        [FieldOffset(44)] public PaWasapiStreamCategory streamCategory;

        [FieldOffset(48)] public PaWasapiStreamOption streamOption;

        [FieldOffset(52)] public PaWasapiStreamPassthrough passthrough;
    }
}
