// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiJackConnectionType
    {
        eJackConnTypeUnknown,
        eJackConnType3Point5mm,
        eJackConnTypeQuarter,
        eJackConnTypeAtapiInternal,
        eJackConnTypeRCA,
        eJackConnTypeOptical,
        eJackConnTypeOtherDigital,
        eJackConnTypeOtherAnalog,
        eJackConnTypeMultichannelAnalogDIN,
        eJackConnTypeXlrProfessional,
        eJackConnTypeRJ11Modem,
        eJackConnTypeCombination
    }
}
