// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiStreamState
    {
        WasapiStreamStateError = 1,
        WasapiStreamStateThreadPrepare = 2,
        WasapiStreamStateThreadStart = 4,
        WasapiStreamStateThreadStop = 8
    }
}
