// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiPassthroughFormat
    {
        ePassthroughFormatPcmIec60958 = 0x0,
        ePassthroughFormatDolbyDigital = 0x920000,
        ePassthroughFormatMpeg1 = 0x30CEA,
        ePassthroughFormatMpeg3 = 0x40CEA,
        ePassthroughFormatMpeg2 = 0x50CEA,
        ePassthroughFormatAac = 0x60CEA,
        ePassthroughFormatDts = 0x80CEA,
        ePassthroughFormatDolbyDigitalPlus = 0xA0CEA,
        ePassthroughFormatDolbyDigitalPlusAtmos = 0x10A0CEA,
        ePassthroughFormatDtsHd = 0xB0CEA,
        ePassthroughFormatDtsXE1 = 0x10B0CEA,
        ePassthroughFormatDtsXE2 = 0x30B0CEA,
        ePassthroughFormatDolbyMlp = 0xC0CEA,
        ePassthroughFormatDolbyMat20 = 0x10C0CEA,
        ePassthroughFormatDolbyMat21 = 0x30C0CEA,
        ePassthroughFormatWmaPro = 0x1640000,
        ePassthroughFormatAtrac = 0x80CEA,
        ePassthroughFormatOneBitAudio = 0x90CEA,
        ePassthroughFormatDst = 0xD0CEA
    }
}
