// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiStreamOption
    {
        eStreamOptionNone = 0,
        eStreamOptionRaw = 1,
        eStreamOptionMatchFormat = 2
    }
}
