// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet
{
    [StructLayout(LayoutKind.Explicit, Size = 72)]
    public unsafe partial struct PaDeviceInfo
    {
        [FieldOffset(0)] public int structVersion;

        [FieldOffset(8)] public byte* name;

        [FieldOffset(16)] public int hostApi;

        [FieldOffset(20)] public int maxInputChannels;

        [FieldOffset(24)] public int maxOutputChannels;

        [FieldOffset(32)] public double defaultLowInputLatency;

        [FieldOffset(40)] public double defaultLowOutputLatency;

        [FieldOffset(48)] public double defaultHighInputLatency;

        [FieldOffset(56)] public double defaultHighOutputLatency;

        [FieldOffset(64)] public double defaultSampleRate;
    }
}
