// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct PaHostApiInfo
    {
        [FieldOffset(0)] public int structVersion;

        [FieldOffset(4)] public PaHostApiTypeId type;

        [FieldOffset(8)] public byte* name;

        [FieldOffset(16)] public int deviceCount;

        [FieldOffset(20)] public int defaultInputDevice;

        [FieldOffset(24)] public int defaultOutputDevice;
    }
}
