// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PortAudioNet
{
    [Flags]
    public enum PaStreamFlags : uint
    {
        NoFlag = 0x0,
        ClipOff = 0x1,
        DitherOff = 0x2,
        NeverDropInput = 0x4,
        PrimeOutputBuffersUsingStreamCallback = 0x8,
        PlatformSpecificFlags = 0xFFFF0000
    }
}
