// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct PaStreamParameters
    {
        [FieldOffset(0)] public int device;

        [FieldOffset(4)] public int channelCount;

        [FieldOffset(8)] public PaSampleFormat sampleFormat;

        [FieldOffset(16)] public double suggestedLatency;

        [FieldOffset(24)] public void* hostApiSpecificStreamInfo;
    }
}
