// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct PaVersionInfo
    {
        [FieldOffset(0)] public int versionMajor;

        [FieldOffset(4)] public int versionMinor;

        [FieldOffset(8)] public int versionSubMinor;

        [FieldOffset(16)] public byte* versionControlRevision;

        [FieldOffset(24)] public byte* versionText;
    }
}
