// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiStreamCategory
    {
        eAudioCategoryOther = 0,
        eAudioCategoryCommunications = 3,
        eAudioCategoryAlerts = 4,
        eAudioCategorySoundEffects = 5,
        eAudioCategoryGameEffects = 6,
        eAudioCategoryGameMedia = 7,
        eAudioCategoryGameChat = 8,
        eAudioCategorySpeech = 9,
        eAudioCategoryMovie = 10,
        eAudioCategoryMedia = 11
    }
}
