// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet.Wasapi
{
    [StructLayout(LayoutKind.Explicit, Size = 16)]
    public unsafe partial struct PaWasapiStreamPassthrough
    {
        [FieldOffset(0)] public PaWasapiPassthroughFormat formatId;

        [FieldOffset(4)] public uint encodedSamplesPerSec;

        [FieldOffset(8)] public uint encodedChannelCount;

        [FieldOffset(12)] public uint averageBytesPerSec;
    }
}
