// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiJackPortConnection
    {
        eJackPortConnJack = 0,
        eJackPortConnIntegratedDevice,
        eJackPortConnBothIntegratedAndJack,
        eJackPortConnUnknown
    }
}
