// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiJackGeoLocation
    {
        eJackGeoLocUnk = 0,
        eJackGeoLocRear = 0x1,
        eJackGeoLocFront,
        eJackGeoLocLeft,
        eJackGeoLocRight,
        eJackGeoLocTop,
        eJackGeoLocBottom,
        eJackGeoLocRearPanel,
        eJackGeoLocRiser,
        eJackGeoLocInsideMobileLid,
        eJackGeoLocDrivebay,
        eJackGeoLocHDMI,
        eJackGeoLocOutsideMobileLid,
        eJackGeoLocATAPI,
        eJackGeoLocReserved5,
        eJackGeoLocReserved6
    }
}
