// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiDeviceRole
    {
        eRoleRemoteNetworkDevice = 0,
        eRoleSpeakers,
        eRoleLineLevel,
        eRoleHeadphones,
        eRoleMicrophone,
        eRoleHeadset,
        eRoleHandset,
        eRoleUnknownDigitalPassthrough,
        eRoleSPDIF,
        eRoleHDMI,
        eRoleUnknownFormFactor
    }
}
