// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet.Wasapi
{
    [StructLayout(LayoutKind.Explicit, Size = 28)]
    public unsafe partial struct PaWasapiJackDescription
    {
        [FieldOffset(0)] public uint channelMapping;

        [FieldOffset(4)] public uint color;

        [FieldOffset(8)] public PaWasapiJackConnectionType connectionType;

        [FieldOffset(12)] public PaWasapiJackGeoLocation geoLocation;

        [FieldOffset(16)] public PaWasapiJackGenLocation genLocation;

        [FieldOffset(20)] public PaWasapiJackPortConnection portConnection;

        [FieldOffset(24)] public uint isConnected;
    }
}
