// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet.Wasapi
{
    public enum PaWasapiFlags
    {
        WinWasapiExclusive = 1,
        WinWasapiRedirectHostProcessor = 2,
        WinWasapiUseChannelMask = 4,
        WinWasapiPolling = 8,
        WinWasapiThreadPriority = 16,
        WinWasapiExplicitSampleFormat = 32,
        WinWasapiAutoConvert = 64,
        WinWasapiPassthrough = 128
    }
}
