// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet
{
    public enum PaHostApiTypeId
    {
        InDevelopment = 0,
        DirectSound = 1,
        MME = 2,
        ASIO = 3,
        SoundManager = 4,
        CoreAudio = 5,
        OSS = 7,
        ALSA = 8,
        AL = 9,
        BeOS = 10,
        WDMKS = 11,
        JACK = 12,
        WASAPI = 13,
        AudioScienceHPI = 14,
        AudioIO = 15,
        PulseAudio = 16,
        Sndio = 17
    }
}
