// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
namespace PortAudioNet
{
    public enum PaStreamCallbackResult
    {
        Continue = 0,
        Complete = 1,
        Abort = 2
    }
}
