// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System.Runtime.InteropServices;

namespace PortAudioNet
{
    [StructLayout(LayoutKind.Explicit, Size = 32)]
    public unsafe partial struct PaStreamInfo
    {
        [FieldOffset(0)] public int structVersion;

        [FieldOffset(8)] public double inputLatency;

        [FieldOffset(16)] public double outputLatency;

        [FieldOffset(24)] public double sampleRate;
    }
}
