// <auto-generated>
// This file was automatically generated by Biohazrd and should not be modified by hand!
// </auto-generated>
#nullable enable
using System;

namespace PortAudioNet
{
    [Flags]
    public enum PaStreamCallbackFlags : uint
    {
        None = 0x0,
        InputUnderflow = 0x1,
        InputOverflow = 0x2,
        OutputUnderflow = 0x4,
        OutputOverflow = 0x8,
        PrimingOutput = 0x10
    }
}
